### ISSUE TITLE
Request for the Addition of 4K Support Option

### ISSUE THREAD

**Issue by faisalhr1997** [Coyote-A/ultimate-upscale-for-automatic1111#1]
We propose the inclusion of an option that allows for 4K support within the extension. When selected, this option would search for and replace occurrences of 2048 with 4096 in the ui-config.json file, followed by a restart of the UI or reload config somehow. If the option is subsequently deselected, the original configurations would be restored. Implementing this feature would greatly enhance the user experience

**Comment by Coyote-A** [comment]
I think the better solution is to add custom width and height sliders in script ui. We will implement this soon

**Comment by faisalhr1997** [comment]
Nice. It's even better now.  Any plan to add batches?

**Comment by Coyote-A** [comment]
Thanks for the offer! we have to research it. This sounds complicated, because our upscaler does not work with a grid of independent tiles, but through many inpaints of a large picture. This is necessary for better convergence of tiles. I'm afraid that when using batches, there will be visible image overlays at the seams. For now, I can advise you to increase the tile size, this should reduce the performance overhead.
